# Table of Contents
### 1. Import libraries and data
### 2. Data Cleaning

## 1. Import libraries and data

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Create path
path = r'/Users/ianfleming/Desktop/World Happiness Report Analysis'

In [3]:
# Import Data
df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'World Happiness Report 2005 - 2023.csv'),index_col = False)

In [4]:
# Check import
df.head()

,Country Name,Regional Indicator,Year,Life Ladder,Log GDP Per Capita,Social Support,Healthy Life Expectancy At Birth,Freedom To Make Life Choices,Generosity,Perceptions Of Corruption,Positive Affect,Negative Affect,Confidence In National Government
0,Afghanistan,South Asia,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,South Asia,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,South Asia,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,South Asia,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,South Asia,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440

In [5]:
df.tail()

,Country Name,Regional Indicator,Year,Life Ladder,Log GDP Per Capita,Social Support,Healthy Life Expectancy At Birth,Freedom To Make Life Choices,Generosity,Perceptions Of Corruption,Positive Affect,Negative Affect,Confidence In National Government
2194,Zimbabwe,Sub-Saharan Africa,2018,3.616480,7.783066,0.775388,52.625000,0.762675,-0.051219,0.844209,0.657524,0.211726,0.550508
2195,Zimbabwe,Sub-Saharan Africa,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.047464,0.830652,0.658434,0.235354,0.456455
2196,Zimbabwe,Sub-Saharan Africa,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.006313,0.788523,0.660658,0.345736,0.577302
2197,Zimbabwe,Sub-Saharan Africa,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.075575,0.756945,0.609917,0.241682,0.665703
2198,Zimbabwe,Sub-Saharan Africa,2022,3.296220,7.670123,0.666172,54.525002,0.651987,-0.069513,0.752632,0.640609,0.191350,NaN

In [6]:
# Check shape
df.shape

(2199, 13)

In [7]:
# Check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2199 entries, 0 to 2198
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country Name                       2199 non-null   object
 1   Regional Indicator                 2087 non-null   object
 2   Year                               2199 non-null   int64
 3   Life Ladder                        2199 non-null   float64
 4   Log GDP Per Capita                 2179 non-null   float64
 5   Social Support                     2186 non-null   float64
 6   Healthy Life Expectancy At Birth   2145 non-null   float64
 7   Freedom To Make Life Choices       2166 non-null   float64
 8   Generosity                         2126 non-null   float64
 9   Perceptions Of Corruption          2083 non-null   float64
 10  Positive Affect                    2175 non-null   float64
 11  Negative Affect                    2183 non-null   float64
 12  Confidence In National Government  1838 non-null   float64
dtypes: float64(10), int64(1), object(2)
memory usage: 223.5+ KB

In [8]:
# Standardise column names
df.columns = (df.columns
    .str.strip()                              # remove trailing spaces
    .str.lower()                              # lowercase everything
    .str.replace(" ", "_")                    # replace spaces with underscores
    .str.replace(r"[^\w\s]", "", regex=True))  # remove special characters

In [9]:
# Check changes
df.head()

,country_name,regional_indicator,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect,confidence_in_national_government
0,Afghanistan,South Asia,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,South Asia,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,South Asia,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,South Asia,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,South Asia,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440

Checking For Missing Values

In [10]:
# Check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2199 entries, 0 to 2198
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   country_name                       2199 non-null   object
 1   regional_indicator                 2087 non-null   object
 2   year                               2199 non-null   int64
 3   life_ladder                        2199 non-null   float64
 4   log_gdp_per_capita                 2179 non-null   float64
 5   social_support                     2186 non-null   float64
 6   healthy_life_expectancy_at_birth   2145 non-null   float64
 7   freedom_to_make_life_choices       2166 non-null   float64
 8   generosity                         2126 non-null   float64
 9   perceptions_of_corruption          2083 non-null   float64
 10  positive_affect                    2175 non-null   float64
 11  negative_affect                    2183 non-null   float64
 12  confidence_in_national_government  1838 non-null   float64
dtypes: float64(10), int64(1), object(2)
memory usage: 223.5+ KB

There is a lot of missing values

## 2. Data Cleaning

In [11]:
# Check missing values
df.isnull().sum()

country_name                           0
regional_indicator                   112
year                                   0
life_ladder                            0
log_gdp_per_capita                    20
social_support                        13
healthy_life_expectancy_at_birth      54
freedom_to_make_life_choices          33
generosity                            73
perceptions_of_corruption            116
positive_affect                       24
negative_affect                       16
confidence_in_national_government    361
dtype: int64

ten of the 13 variables have missing values that need addressing.

Addressing Missing Values

There is a large amount of missing values in confidence_in_national_government column. I don't want to replace the missing values so creating a flag column.

FIRST MISSING

In [12]:
# Create missing flag column
df["conf_gov_missing"] = df["confidence_in_national_government"].isnull().astype(int)

In [13]:
# Check flag column
df[["confidence_in_national_government", "conf_gov_missing"]].head(10)

   confidence_in_national_government  conf_gov_missing
0                           0.612072                 0
1                           0.611545                 0
2                           0.299357                 0
3                           0.307386                 0
4                           0.435440                 0
5                           0.482847                 0
6                           0.409048                 0
7                           0.260557                 0
8                           0.324990                 0
9                           0.261179                 0

Addressing regional_indicator column which has 112 missing values

SECOND MISSING

In [14]:
# Fill missing values with "Unknown"
df["regional_indicator"] = df["regional_indicator"].fillna("Unknown")

In [15]:
# Check for missing values
df["regional_indicator"].isnull().sum()

0

gdp per capita has 20 missing values. As it is not so many and is numeric, I will impute the mean

THIRD MISSING

In [16]:
# Impute GDP with the mean
df["log_gdp_per_capita"] = df["log_gdp_per_capita"].fillna(df["log_gdp_per_capita"].mean())

In [17]:
# Check values
df["log_gdp_per_capita"].isnull().sum()

0

FOURTH MISSING

In [18]:
df[df["healthy_life_expectancy_at_birth"].isnull()]

,country_name,regional_indicator,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect,confidence_in_national_government,conf_gov_missing
793,Hong Kong S.A.R. of China,East Asia,2006,5.511187,10.746400,0.812178,NaN,0.909820,0.151303,0.355985,0.591140,0.235955,0.663938,0
794,Hong Kong S.A.R. of China,East Asia,2008,5.137262,10.815522,0.840222,NaN,0.922211,0.291946,0.273945,0.575073,0.236634,0.677437,0
795,Hong Kong S.A.R. of China,East Asia,2009,5.397056,10.788470,0.834716,NaN,0.918026,0.303338,0.272125,0.606459,0.210104,0.619142,0
796,Hong Kong S.A.R. of China,East Asia,2010,5.642835,10.846611,0.857314,NaN,0.890418,0.327606,0.255775,0.600561,0.183106,0.634737,0
797,Hong Kong S.A.R. of China,East Asia,2011,5.474011,10.886909,0.846060,NaN,0.894330,0.230172,0.244887,0.582491,0.195712,0.584562,0
798,Hong Kong S.A.R. of China,East Asia,2012,5.483765,10.892731,0.826426,NaN,0.879752,0.218014,0.379783,0.580223,0.183349,0.497906,0
799,Hong Kong S.A.R. of China,East Asia,2014,5.458051,10.939480,0.833558,NaN,0.843082,0.219372,0.422960,0.602495,0.242868,0.457823,0
800,Hong Kong S.A.R. of China,East Asia,2016,5.498421,10.969893,0.832078,NaN,0.799743,0.095778,0.402813,0.568555,0.213115,0.449610,0
801,Hong Kong S.A.R. of China,East Asia,2017,5.362475,10.999467,0.831066,NaN,0.830657,0.135592,0.415810,0.535812,0.200593,0.545041,0
802,Hong Kong S.A.R. of China,East Asia,2019,5.659317,10.995218,0.855826,NaN,0.726852,0.063232,0.431974,0.519312,0.357607,0.332540,0
803,Hong Kong S.A.R. of China,East Asia,2020,5.295341,10.931117,0.812943,NaN,0.705452,-0.074210,0.380351,0.521671,0.210314,0.442211,0
804,Hong Kong S.A.R. of China,East Asia,2021,5.321551,11.001736,0.821089,NaN,0.668631,0.022381,0.389589,0.534148,0.223565,0.495274,0
1031,Kosovo,Central and Eastern Europe,2007,5.103906,9.389766,0.847812,NaN,0.381364,NaN,0.894462,0.613723,0.236699,0.375601,0
1032,Kosovo,Central and Eastern Europe,2008,5.521660,8.858291,0.883843,NaN,NaN,0.096545,0.849059,0.499646,0.317828,0.549438,0
1033,Kosovo,Central and Eastern Europe,2009,5.891433,8.899382,0.830427,NaN,0.506415,0.205565,0.967839,0.527557,0.168830,NaN,1
1034,Kosovo,Central and Eastern Europe,2010,5.176601,8.939567,0.707959,NaN,0.451444,0.173606,0.967272,0.672983,0.117717,NaN,1
1035,Kosovo,Central and Eastern Europe,2011,4.859502,8.992258,0.759102,NaN,0.588979,0.006247,0.919212,0.603740,0.124438,NaN,1
1036,Kosovo,Central and Eastern Europe,2012,5.639588,9.000282,0.757147,NaN,0.635793,0.030489,0.949651,0.561854,0.099630,0.312399,0
1037,Kosovo,Central and Eastern Europe,2013,6.125758,9.046240,0.720750,NaN,0.568463,0.116873,0.935095,0.649957,0.202731,0.361421,0
1038,Kosovo,Central and Eastern Europe,2014,5.000375,9.082124,0.705632,NaN,0.441391,0.012549,0.775201,0.551719,0.205950,0.344450,0
1039,Kosovo,Central and Eastern Europe,2015,5.077461,9.153252,0.805271,NaN,0.561048,0.180007,0.850647,0.684578,0.179989,0.328998,0
1040,Kosovo,Central and Eastern Europe,2016,5.759412,9.213440,0.823803,NaN,0.827399,0.122952,0.940898,0.588413,0.149607,0.313765,0
1041,Kosovo,Central and Eastern Europe,2017,6.149200,9.253033,0.792087,NaN,0.857677,0.114815,0.925192,0.616912,0.185879,0.298196,0
1042,Kosovo,Central and Eastern Europe,2018,6.391826,9.283142,0.822407,NaN,0.889737,0.266691,0.922078,0.642224,0.170248,0.347547,0
1043,Kosovo,Central and Eastern Europe,2019,6.425144,9.334190,0.842511,NaN,0.841190,0.244229,0.920297,0.611600,0.140792,0.308195,0
1044,Kosovo,Central and Eastern Europe,2020,6.294414,9.278607,0.792374,NaN,0.879838,0.304365,0.909894,0.592678,0.201458,0.247848,0
1045,Kosovo,Central and Eastern Europe,2021,6.648499,9.382963,0.848839,NaN,0.840117,0.260641,0.842379,0.578284,0.116078,0.577199,0
1046,Kosovo,Central and Eastern Europe,2022,6.159853,9.415709,0.887639,NaN,0.864866,0.211152,0.845950,0.549290,0.142420,NaN,1
1755,Somaliland region,Unknown,2009,4.991400,9.389766,0.879567,NaN,0.746304,NaN,0.513372,0.707874,0.112012,0.538495,0
1756,Somaliland region,Unknown,2010,4.657363,9.389766,0.829005,NaN,0.820182,NaN,0.471094,0.631947,0.083426,0.587192,0
1757,Somaliland region,Unknown,2011,4.930572,9.389766,0.787962,NaN,0.858104,NaN,0.357341,0.690514,0.122244,0.760764,0
1758,Somaliland region,Unknown,2012,5.057314,9.389766,0.786291,NaN,0.758219,NaN,0.333832,0.686732,0.152428,0.651242,0
1833,State of Palestine,Unknown,2011,4.751220,8.451591,0.750832,NaN,0.521889,-0.127747,0.750208,0.499074,0.387651,NaN,1
1834,State of Palestine,Unknown,2012,4.646608,8.598372,0.782169,NaN,0.541583,-0.160553,0.730194,0.559733,0.378504,NaN,1
1835,State of Palestine,Unknown,2013,4.844028,8.594526,0.760900,NaN,0.453903,-0.160124,0.779646,0.536739,0.365276,NaN,1
1836,State of Palestine,Unknown,2014,4.721938,8.618412,0.775087,NaN,0.657050,-0.160567,0.804165,0.504632,0.380452,NaN,1
1837,State of Palestine,Unknown,2015,4.695239,8.683147,0.766101,NaN,0.556041,-0.169831,0.774301,0.536447,0.369085,NaN,1
1838,State of Palestine,Unknown,2016,4.906618,8.737954,0.817771,NaN,0.607669,-0.148602,0.812465,0.543776,0.377642,NaN,1
1839,State of Palestine,Unknown,2017,4.628133,8.733621,0.824345,NaN,0.631611,-0.182863,0.830646,0.533918,0.416072,NaN,1
1840,State of Palestine,Unknown,2018,4.553922,8.717741,0.819479,NaN,0.654535,-0.159904,0.813780,0.528392,0.418929,NaN,1
1841,State of Palestine,Unknown,2019,4.482537,8.716377,0.832550,NaN,0.653488,-0.132370,0.829283,0.538073,0.399672,NaN,1
1842,State of Palestine,Unknown,2022,4.907760,9.389766,0.859655,NaN,0.694853,NaN,0.835795,0.584111,0.361776,NaN,1
1888,Taiwan Province of China,East Asia,2011,6.308915,10.693417,0.862521,NaN,0.761488,0.031887,0.754584,0.727106,0.112288,0.472067,0
1889,Taiwan Province of China,East Asia,2012,6.125917,10.717881,0.825072,NaN,0.698195,0.017363,0.802829,0.701637,0.140011,0.335142,0
1890,Taiwan Province of China,East Asia,2013,6.340344,10.723532,0.816993,NaN,0.690071,-0.000835,0.841232,0.754478,0.124445,0.264499,0
1891,Taiwan Province of China,East Asia,2014,6.363497,10.749411,0.870012,NaN,0.692900,0.091174,0.865741,0.767370,0.108366,0.270723,0
1892,Taiwan Province of China,East Asia,2015,6.450088,10.778760,0.885389,NaN,0.700810,0.018902,0.857195,0.750358,0.129349,0.270260,0
1893,Taiwan Province of China,East Asia,2016,6.512851,10.768047,0.894989,NaN,0.718925,-0.046887,0.810521,0.742680,0.108305,0.404713,0
1894,Taiwan Province of China,East Asia,2017,6.359451,10.774066,0.891119,NaN,0.759655,-0.067865,0.742780,0.715303,0.114123,0.322822,0
1895,Taiwan Province of China,East Asia,2018,6.467005,10.780802,0.896459,NaN,0.741033,-0.176948,0.735971,0.745919,0.092696,0.311723,0
1896,Taiwan Province of China,East Asia,2019,6.537090,10.797460,0.893431,NaN,0.814484,-0.128958,0.718112,0.762097,0.093412,0.431495,0
1897,Taiwan Province of China,East Asia,2020,6.751068,9.389766,0.900833,NaN,0.798835,NaN,0.710567,0.743169,0.082737,0.579727,0
1898,Taiwan Province of China,East Asia,2021,6.246744,9.389766,0.866298,NaN,0.818467,NaN,0.675439,0.667417,0.122980,0.437148,0
1899,Taiwan Province of China,East Asia,2022,6.607147,9.389766,0.882820,NaN,0.800192,NaN,0.657556,0.716587,0.095399,NaN,1

healthy_life_expectancy_at_birth has 54 NaNs so I will impute them with the mean

In [19]:
# Impute life expectancy with the mean
df["healthy_life_expectancy_at_birth"] = df["healthy_life_expectancy_at_birth"].fillna(df["healthy_life_expectancy_at_birth"].mean())

In [20]:
# Check impute
df["healthy_life_expectancy_at_birth"].isnull().sum()

0

FIFTH MISSING

In [21]:
# Check missing values for social_support
df[df["social_support"].isnull()]

,country_name,regional_indicator,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect,confidence_in_national_government,conf_gov_missing
29,Algeria,Middle East and North Africa,2010,5.463567,9.306355,NaN,65.500000,0.592696,-0.209753,0.618038,NaN,NaN,NaN,1
126,Bahrain,Middle East and North Africa,2014,6.165134,10.801981,NaN,65.959999,NaN,NaN,NaN,NaN,NaN,NaN,1
328,Canada,North America and ANZ,2007,7.481753,10.733970,NaN,70.620003,0.930341,0.245596,0.405608,0.811577,0.256810,0.637824,0
524,Djibouti,Unknown,2010,5.005811,7.934187,NaN,54.599998,0.763730,-0.068953,0.596910,NaN,NaN,0.692278,0
1053,Kuwait,Middle East and North Africa,2014,6.180139,10.925643,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,1
1323,Morocco,Middle East and North Africa,2010,4.383247,8.672808,NaN,62.500000,0.662900,-0.159650,0.900453,NaN,NaN,NaN,1
1485,Oman,Unknown,2011,6.852982,10.538620,NaN,62.340000,0.916293,0.009673,NaN,NaN,0.295164,NaN,1
1599,Qatar,Unknown,2010,6.849653,11.551208,NaN,64.699997,NaN,0.096500,NaN,NaN,NaN,NaN,1
1602,Qatar,Unknown,2015,6.374529,11.532454,NaN,66.400002,NaN,NaN,NaN,NaN,NaN,NaN,1
1966,Tunisia,Middle East and North Africa,2009,5.025470,9.237887,NaN,66.220001,0.781496,-0.124444,0.722211,NaN,NaN,NaN,1
2045,United Arab Emirates,Middle East and North Africa,2014,6.539855,11.071845,NaN,65.339996,NaN,NaN,NaN,NaN,NaN,NaN,1
2072,United States,North America and ANZ,2007,7.512688,10.931180,NaN,66.760002,0.871904,0.192796,0.633035,0.755915,0.231679,0.393245,0
2149,Vietnam,Southeast Asia,2017,5.175279,9.110596,NaN,65.099998,NaN,NaN,NaN,NaN,NaN,NaN,1

social_support has 13 missing values so will impute the mean

In [22]:
# Impute social support with the mean
df["social_support"] = df["social_support"].fillna(df["social_support"].mean())

In [23]:
# Check impute
df["social_support"].isnull().sum()

0

SIXTH MISSING

In [24]:
# Check missing values for freedom_to_make_life_choices
df[df["freedom_to_make_life_choices"].isnull()]

,country_name,regional_indicator,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect,confidence_in_national_government,conf_gov_missing
32,Algeria,Middle East and North Africa,2014,6.354898,9.355415,0.818189,65.900002,NaN,NaN,NaN,0.558359,0.176866,NaN,1
33,Algeria,Middle East and North Africa,2016,5.340854,9.383312,0.748588,66.099998,NaN,NaN,NaN,0.565026,0.377112,NaN,1
126,Bahrain,Middle East and North Africa,2014,6.165134,10.801981,0.810679,65.959999,NaN,NaN,NaN,NaN,NaN,NaN,1
293,Cambodia,Southeast Asia,2006,3.568745,7.746443,0.793081,57.639999,NaN,0.253480,0.829181,NaN,0.341023,0.736355,0
381,China,East Asia,2006,4.560495,8.696139,0.747011,65.660004,NaN,NaN,NaN,0.657659,0.169580,NaN,1
382,China,East Asia,2007,4.862862,8.823968,0.810852,65.919998,NaN,-0.178883,NaN,0.663977,0.158614,NaN,1
389,China,East Asia,2014,5.195619,9.380201,0.820366,67.739998,NaN,-0.219485,NaN,0.709763,0.111518,NaN,1
390,China,East Asia,2015,5.303878,9.442431,0.793734,68.000000,NaN,-0.247149,NaN,0.666827,0.171315,NaN,1
391,China,East Asia,2016,5.324956,9.502946,0.741703,68.125000,NaN,-0.230264,NaN,0.683256,0.145625,NaN,1
562,Egypt,Middle East and North Africa,2008,4.631741,9.134907,0.738364,61.580002,NaN,-0.086289,0.913642,0.627448,0.301018,NaN,1
885,Iraq,Middle East and North Africa,2013,4.725017,9.159455,0.728285,60.840000,NaN,-0.044170,0.709726,NaN,0.554279,0.500670,0
980,Jordan,Middle East and North Africa,2005,6.294660,9.282825,0.920013,65.800003,NaN,NaN,0.669727,0.629833,0.239560,0.800150,0
982,Jordan,Middle East and North Africa,2008,4.930058,9.353609,0.766224,66.339996,NaN,-0.131128,0.709403,0.655700,0.331201,NaN,1
1032,Kosovo,Central and Eastern Europe,2008,5.521660,8.858291,0.883843,63.294583,NaN,0.096545,0.849059,0.499646,0.317828,0.549438,0
1053,Kuwait,Middle East and North Africa,2014,6.180139,10.925643,0.810679,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,1
1079,Laos,Southeast Asia,2012,4.876085,8.600584,0.692628,58.160000,NaN,0.230367,NaN,0.740587,0.386679,NaN,1
1167,Madagascar,Sub-Saharan Africa,2006,3.979751,7.351137,0.711135,54.139999,NaN,-0.038258,NaN,0.562594,0.161333,0.713698,0
1599,Qatar,Unknown,2010,6.849653,11.551208,0.810679,64.699997,NaN,0.096500,NaN,NaN,NaN,NaN,1
1602,Qatar,Unknown,2015,6.374529,11.532454,0.810679,66.400002,NaN,NaN,NaN,NaN,NaN,NaN,1
1648,Saudi Arabia,Middle East and North Africa,2005,7.079644,10.674833,0.867819,61.200001,NaN,NaN,0.505149,0.680691,0.242553,NaN,1
1664,Saudi Arabia,Middle East and North Africa,2022,6.381610,10.780560,0.900105,64.599998,NaN,-0.027261,NaN,0.677459,0.204956,NaN,1
1912,Tajikistan,Commonwealth of Independent States,2018,5.497469,8.133027,0.875243,61.849998,NaN,-0.070537,0.577946,0.631739,0.219794,NaN,1
1913,Tajikistan,Commonwealth of Independent States,2019,5.464015,8.181799,0.879823,62.000000,NaN,-0.050671,0.490029,0.663063,0.178497,NaN,1
1914,Tajikistan,Commonwealth of Independent States,2020,5.373399,8.203014,0.789745,62.150002,NaN,-0.051335,0.549786,0.651894,0.344161,NaN,1
1915,Tajikistan,Commonwealth of Independent States,2021,5.286824,8.269583,0.882889,62.299999,NaN,-0.068064,0.498925,0.655013,0.240200,NaN,1
1996,Turkmenistan,Commonwealth of Independent States,2009,6.567713,8.955209,0.923846,59.779999,NaN,-0.102010,NaN,0.695308,0.151584,NaN,1
1997,Turkmenistan,Commonwealth of Independent States,2011,5.791755,9.146244,0.964419,60.419998,NaN,0.018016,NaN,0.576616,0.122068,NaN,1
2045,United Arab Emirates,Middle East and North Africa,2014,6.539855,11.071845,0.810679,65.339996,NaN,NaN,NaN,NaN,NaN,NaN,1
2107,Uzbekistan,Commonwealth of Independent States,2009,5.260721,8.462947,0.904678,62.060001,NaN,0.006301,0.610258,0.646040,0.158657,NaN,1
2108,Uzbekistan,Commonwealth of Independent States,2010,5.095342,8.507943,0.903226,62.299999,NaN,-0.036958,0.518720,0.664853,0.151883,NaN,1
2146,Vietnam,Southeast Asia,2014,5.084923,8.941402,0.792168,64.820000,NaN,-0.018801,NaN,0.633852,0.240607,NaN,1
2147,Vietnam,Southeast Asia,2015,5.076315,8.998519,0.848677,64.900002,NaN,0.066410,NaN,0.583119,0.232416,NaN,1
2149,Vietnam,Southeast Asia,2017,5.175279,9.110596,0.810679,65.099998,NaN,NaN,NaN,NaN,NaN,NaN,1

In [25]:
# Impute freedom with the mean
df["freedom_to_make_life_choices"] = df["freedom_to_make_life_choices"].fillna(
    df["freedom_to_make_life_choices"].mean())

In [26]:
# Check impute
df["freedom_to_make_life_choices"].isnull().sum()

0

SEVENTH MISSING

Generosity has 73 missing values

In [27]:
# Impute generosity with the mean
df["generosity"] = df["generosity"].fillna(df["generosity"].mean())

In [28]:
# Check
df["generosity"].isnull().sum()

0

EIGTH MISSING

Perceptions_of_corruption has 116 misisng values

In [29]:
# Impute perceptions of corruption with the mean
df["perceptions_of_corruption"] = df["perceptions_of_corruption"].fillna(
    df["perceptions_of_corruption"].mean())

In [30]:
# Check
df["perceptions_of_corruption"].isnull().sum()

0

NINTH MISSING

Positive_affect has 19 missing values

In [31]:
# Impute positive_affect with the mean
df["positive_affect"] = df["positive_affect"].fillna(df["positive_affect"].mean())

In [32]:
# Check impute
df["positive_affect"].isnull().sum()

0

TENTH MISSING

Negative_affect has 16 missing

In [33]:
# Impute negative affect with the mean
df["negative_affect"] = df["negative_affect"].fillna(df["negative_affect"].mean())

In [34]:
# Check impute
df["negative_affect"].isnull().sum()

0

Now the data has 0 missing values except in the column "confidence_in_national_government" which I have created a flag column called "conf_gov_missing"

In [35]:
# Check missing values
df.isnull().sum()

country_name                           0
regional_indicator                     0
year                                   0
life_ladder                            0
log_gdp_per_capita                     0
social_support                         0
healthy_life_expectancy_at_birth       0
freedom_to_make_life_choices           0
generosity                             0
perceptions_of_corruption              0
positive_affect                        0
negative_affect                        0
confidence_in_national_government    361
conf_gov_missing                       0
dtype: int64

CHECK FOR DUPLICATES

In [36]:
# Check duplicate rows
df.duplicated().sum()

0

DESCRIPTIVE STATISTICS

In [37]:
# Descriptive stats for all numeric columns
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,2199.0,2014.161437,4.718736,2005.000000,2010.000000,2014.000000,2018.000000,2022.000000
life_ladder,2199.0,5.479226,1.125529,1.281271,4.646750,5.432437,6.309460,8.018934
log_gdp_per_capita,2199.0,9.389766,1.148128,5.526723,8.505131,9.491772,10.366237,11.663788
social_support,2199.0,0.810679,0.120594,0.228217,0.747512,0.834280,0.904607,0.987343
healthy_life_expectancy_at_birth,2199.0,63.294583,6.815805,6.720000,59.412500,64.879997,68.329998,74.474998
freedom_to_make_life_choices,2199.0,0.747858,0.139094,0.257534,0.658615,0.766945,0.857775,0.985178
generosity,2199.0,0.000096,0.158385,-0.337527,-0.107358,-0.016512,0.086938,0.702708
perceptions_of_corruption,2199.0,0.745195,0.180867,0.035198,0.697610,0.791269,0.865565,0.983276
positive_affect,2199.0,0.652143,0.105342,0.178886,0.572742,0.661645,0.736762,0.883586
negative_affect,2199.0,0.271501,0.086559,0.082737,0.208157,0.261508,0.322382,0.704590
confidence_in_national_government,1838.0,0.483999,0.193071,0.068769,0.332549,0.467140,0.618846,0.993604
conf_gov_missing,2199.0,0.164166,0.370510,0.000000,0.000000,0.000000,0.000000,1.000000

In [38]:
# Check shape of data
df.shape

(2199, 14)

In [39]:
# Export cleaned data
df.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'world_happiness_report.csv'))